# Generated by Django 5.2.5 on 2025-08-22 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='')),
                ('price_type', models.CharField(choices=[('fixed', 'قیمت ثابت'), ('negotible', 'قیمت توافقی')], default='fixed', max_length=30, verbose_name='')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='')),
                ('title', models.CharField(max_length=100, verbose_name='')),
                ('description', models.CharField(max_length=500, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='')),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='product_module.plan', verbose_name='')),
            ],
        ),
    ]
