# Generated by Django 5.2.5 on 2025-08-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': '', 'verbose_name_plural': ''},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'نمونه کار', 'verbose_name_plural': 'نمونه کار ها'},
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price_type',
            field=models.CharField(choices=[('fixed', 'قیمت ثابت'), ('negotible', 'قیمت توافقی')], default='fixed', max_length=30, verbose_name='انتخاب نوع قیمت'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=500, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
    ]
