# Generated by Django 5.2.5 on 2025-08-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_alter_plan_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'توضیحات پلن', 'verbose_name_plural': 'توضیحات پلن ها'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'پلن', 'verbose_name_plural': 'پلن ها'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
