# Generated by Django 5.2.5 on 2025-08-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0005_alter_feature_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='قیمت'),
        ),
    ]
