# Generated by Django 5.2.5 on 2025-08-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('url', models.URLField(verbose_name='لینک')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='ایکون')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
            ],
            options={
                'verbose_name': 'شبکه احتماعی',
                'verbose_name_plural': 'شبکه های احتماعی',
            },
        ),
        migrations.CreateModel(
            name='UseFulLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('url', models.URLField(verbose_name='لینک')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
            ],
            options={
                'verbose_name': 'لینک مفید',
                'verbose_name_plural': 'لینک های مفید',
            },
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'اطالاعات تماس ما', 'verbose_name_plural': 'اطلاعات تماس ما'},
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='message',
            field=models.TextField(verbose_name='توضیج'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='شماره تماس   '),
        ),
    ]
