# Generated by Django 5.2.5 on 2025-08-25 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0002_socialmedia_usefullink_alter_contactinfo_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialMedia',
        ),
        migrations.DeleteModel(
            name='UseFulLink',
        ),
    ]
