# Generated by Django 5.2.5 on 2025-08-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='site_setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=50, verbose_name='نام شرکت')),
                ('office_about', models.TextField(verbose_name='درباره شرکت')),
                ('banner_title', models.CharField(max_length=100, verbose_name='عنوان بنر')),
                ('about_title', models.CharField(max_length=200, verbose_name='عنوان درباره ما')),
                ('about_description1', models.TextField(verbose_name='توضیحات اول درباره ما')),
                ('about_image', models.ImageField(upload_to='about/', verbose_name='')),
            ],
        ),
    ]
