# Generated by Django 5.2.5 on 2025-08-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_about', models.TextField(verbose_name='درباره ما/فوتر')),
            ],
        ),
        migrations.AlterModelOptions(
            name='site_setting',
            options={'verbose_name': 'تنظیمات سایت', 'verbose_name_plural': 'تنظیمات سایت'},
        ),
    ]
