# Generated by Django 5.2.5 on 2025-08-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0002_footersite_alter_site_setting_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('url', models.URLField(verbose_name='لینک')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='ایکون')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
            ],
            options={
                'verbose_name': 'شبکه احتماعی',
                'verbose_name_plural': 'شبکه های احتماعی',
            },
        ),
        migrations.CreateModel(
            name='UseFulLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('url', models.URLField(verbose_name='لینک')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
            ],
            options={
                'verbose_name': 'لینک مفید',
                'verbose_name_plural': 'لینک های مفید',
            },
        ),
    ]
