# Generated by Django 5.2.5 on 2025-08-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0004_license'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterSite',
        ),
        migrations.AddField(
            model_name='site_setting',
            name='footer_about',
            field=models.TextField(default=1, verbose_name='درباره ما/فوتر'),
            preserve_default=False,
        ),
    ]
