# Generated by Django 5.2.5 on 2025-08-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='')),
                ('image', models.ImageField(upload_to='articles/', verbose_name='')),
                ('short_desc', models.CharField(max_length=300, verbose_name='')),
                ('content', models.TextField(verbose_name='')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
                'ordering': ['-created_at'],
            },
        ),
    ]
