# Generated by Django 5.2.5 on 2025-08-22 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0002_alter_article_content_alter_article_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at'], 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
    ]
